### PR TITLE
Bugfix/version

### PR DESCRIPTION
**Pull request by KBurroughs**
# Changelog
This is a PR to fix the version and fingerprint display issue on the home screen. 

For testing continousIntegration task method:

`./gradlew continuousIntegration -Pfingerprint=DEVTEST -PbuildNumber=222 -PdisablePreDex`

then install apk from `app/build/outputs/apk/dev/debug/`

For testing system env method:

Add custom env variables `BITRISE_BUILD_NUMBER` (with integer value) and `BITRISE_VERSION_FINGERPRINT` (with String value) to your local machine's system env.

Perform usual 'Run' to install

## Added
-

## Changed
- `build.gradle.kts`
- `build.gradle.kts` (app)
- `MainViewModel.kt`
- `MainViewModelTest.kt`

## Removed
-

## Is there test coverage for your changes?
Yes

## Screenshots
bugfix-version

### CODE REVIEW

**Comment by KBurroughs** [comment]
In the transition to kts, I think we lost the continuousIntegration task. I made a slight adjustment so that the task can now be called from the Gradle task menu in Android Studio. The original implementation assumes the build server will pass in args at build time - I'm not exactly sure how this works - and those values would be apart of the project properties. I looked and looked, but couldn't figure out how to emulate that behavior. I found a different suggestion that used system environment variables instead. This was easy to emulate on my local machine and I understand where the values would be implemented on Bitrise, so I decided to add that logic as an alternate suggestion for devs. I'm not saying the system env values are the best play here, but it was the only way I could emulate it myself. This was my first dive into the build server, so I'm open to any suggestions on best practices or alternate methods.

**Comment by KBurroughs** [comment]
Of course, I figure out how to perform the other method after I draft up my PR!

**Comment by KBurroughs** [comment]
I swapped back to the reference branch and realized the original implementation for the continousIntegration task was working properly, so I've reverted that little bit of code. I must have been hasty and missed it in the Gradle task list. But the README says you can run `continuousIntegration -Pfingerprint=%build.vcs.number% -PbuildNumber=%build.counter% -PdisablePreDex` but that doesn't work for local testing. It requires ./gradlew in front, which is not something I knew beforehand. Now that I run it as `./gradlew continuousIntegration -Pfingerprint=DEVTEST -PbuildNumber=222 -PdisablePreDex` (subbing in test values) it works just fine.

**Comment by bradyjohnk** [comment]
I like this. Looks like a much needed update!

**Review by Brandon-Wolff — APPROVED** [review]

**Pull request merged**
