### PR TITLE
Alias continuousIntegration

### PR DESCRIPTION
**Pull request by weverb2**
@patrickhammond @atoennis @stuartsoft 

continuousIntegration is hard to type.

### CODE REVIEW

**Comment by stuartsoft** [comment]
you should alias `spoonDevDebugAndroidTest` and `staticAnalysis`

**Comment by weverb2** [comment]
@stuartsoft What would they be aliased to?

And we should get  @patrickhammond's 👍  before aliasing everything 😄

**Comment by patrickhammond** [comment]
I guess I haven't felt this pain because I have `alias ci='./gradlew continuousIntegration'` to my bash profile.  Saves needing to also type the Gradle stuff too.  Thoughts on if we want to move in the direction of having team dotfiles?

**Comment by stuartsoft** [comment]
@patrickhammond that would actually be pretty nice to have team dotfiles. It would also let us alias gradle commands globally, rather than on a per-project basis.

**Comment by weverb2** [comment]
Closing this and opening: https://trello.com/c/3e9TbwKW

**Pull request closed without merging**
